### ISSUE TITLE
Feedback after initial testing

### ISSUE THREAD

**Issue by dkozinn** [cwhelchel/hunterlog#2]
I've been doing some testing and wanted to provide feedback. As per our discussing in Slack (I'm K2DBK), I'm posting this here so that it doesn't get lost. 

	• Display
		○ Too much unused space vertically, can only get a few parks listed.
		○ Multiple activator comments push down park list much farther (see screenshot)
			§ Even without lots of comments pam takes up around 1/3 of the display
			§ Possibly add timestamps or limit to last 'x' hours?
			
	• Configuration:
		○ Add comments or method to indicate "I don’t use this" for FLRIG & ADIF
			§ Should be able to disable anything that could use a port to reduce chance of conflict with other software
	• Stats:
		○ Move this to under Configuration or at least change to "import stats".
		○ Add some kind of progress indicator when importing Park stats (LONG time)
		○ I don't have any reasonable way to export the park info into an ADIF file, my logger (DX4WIN) doesn't support that. Is there a way to grab the info directly from POTA (even if it requires supplying credentials)?
	• Can there be an indicator for new (to me) parks instead of just leaving it blank?
	• Filters
		○ Enhancement - Allow multiple selections per filter (e.g., allow FT-4 and FT-8 at the same time)
	• Startup
		○ Doesn't restore window size/position
		○ Opens devtools (presumably intentional but wanted to mention)
		○ Column sort order not retained when re-starting
	• Entering data
		○ Not an issue for clicking on parks but for manual entry:
			§ Callsign should uppercase
			§ Mode should have a dropdown
			§ Input validation ?
	• Misc
		○ Clicking on Export Logged QSOs or Export Park Info should provide some feedback that it worked

![image](https://github.com/cwhelchel/hunterlog/assets/8498054/83bf0ef6-f9e6-47f2-8397-ece5a79ed13c)

**Comment by cwhelchel** [comment]
This is excellent feedback! Thanks for taking the time to write them up, David.

Pretty much all you have listed is valid with some points I want to add:

**The vertical space taken up by activator comments:** This has been addressed (somewhat) in [the latest pre-release version](https://github.com/cwhelchel/hunterlog/releases/tag/v0.0.1k)
I _think_ your screen shot is from the older version. Hard to know there's a new one since github doesn't put the prerelease tags as latest. It should scroll the activator comments in the newest one.

The issue with it being 1/3 vertical space even without the comments is a fair point. The map display is the biggest offender here. It's possible I could shrink it. 

**Add some kind of progress indicator when importing Park stats (LONG time)** Did the spinning circle not show up? You can test by opening the 'OP STATS' and it should show the spinner while you look for a file. You can cancel from the Open File Dialog

**Can there be an indicator for new (to me) parks instead of just leaving it blank?** I would actually like to add a filter for them. So you can see _only_ new parks. There's a new indicator in the newest release as well.

**Opens devtools (presumably intentional but wanted to mention)**: yes, it's intentional. Going to leave that open for prereleases to show the Javascript console. It's safe to close though.

**Comment by dkozinn** [comment]
I've installed the most recent version (0.0.1k) and you are correct, the screenshot was from the previous version.  Responding to your comments:

I haven't run into an activation since installing that had enough comments to have to scroll, but I'll pay attention to that. Even without lots of comments I'm still only getting 8 or 9 parks listed. (Windows 10, 1920 x 1080, standard font sizes (not scaled).

Regarding vertical space in general, is it possible to reduce the size of height on individual rows? I know it's a compromise between visibility and maximum information density. Maybe a user-configuration, like some other apps (Outlook, gmail, etc.) have?

> Did the spinning circle not show up? 

It did, but because it took a while, I wasn't sure if anything was actually happening.

> Can there be an indicator for new (to me) parks instead of just leaving it blank? **I would actually like to add a filter for them.**

Even better!

**New Feedback**

* None of the filter settings are retained after a restart

**Comment by cwhelchel** [comment]
I think this is ready to be closed. Anything not listed can be re-opend in the future as a separate enhancement or bug.

**Comment by dkozinn** [comment]
Thanks for implementing all this. I'll try to do some testing and provide feedback either here or on Discord (just joined there).
